Algoritmo "testando registro"

tipo

   data=registro
      dia,mes,ano:inteiro
   fimregistro

//   cadastro=registro
//      rg:inteiro
//      nome:caracter
//      dataconta:data
//   fimregistro

Var
//   vetorcliente: vetor[1..5] de cadastro
   dataconta:data
Inicio

//  leia (vetorcliente[1].dia)
//  escreva (vetorcliente[1].dia)

leia (dataconta.dia)
leia (dataconta.mes)
leia (dataconta.ano)

escreva (dataconta.dia)
escreva (dataconta.mes)
escreva (dataconta.ano)
Fimalgoritmo